include: package:lint/analysis_options.yaml

# Not happy with the default? Customize the rules depending on your needs.
# Here are some examples:
linter:
  rules:
    # Given
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true
    sort_constructors_first: true

    # Mine
    avoid_print: false
    curly_braces_in_flow_control_structures: false
    no_runtimeType_toString: false
    only_throw_errors: true
    require_trailing_commas: false
