include: package:lint/analysis_options.yaml

# Not happy with the default? Customize the rules depending on your needs.
# Here are some examples:
linter:
  rules:
    # Given
    sort_constructors_first: true
    prefer_single_quotes: true
    avoid_classes_with_only_static_members: false

    # Mine
    only_throw_errors: true
    require_trailing_commas: false
    avoid_print: false