name: crypto_trader
description: Easy crypto trading

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0
  provider: ^6.0.0
  path_provider: ^2.0.3
  fl_chart: ^0.40.0
  synchronized: ^3.0.0
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - config/evgb.json
    - config/all.json
